package com.vsulimov.libsubsonic.url

import com.vsulimov.libsubsonic.auth.SubsonicAuthenticator
import java.net.URLEncoder

/**
 * Builds fully qualified Subsonic REST API URLs and injects authentication parameters.
 *
 * Holds the server base URL and the current credentials, and produces signed URLs for
 * every endpoint by appending `f=json`, the caller-supplied query parameters and the
 * `u`/`s`/`t`/`v`/`c` authentication parameters generated by [SubsonicAuthenticator].
 *
 * @property baseUrl The root URL of the Subsonic server. Trailing slash is optional.
 * @property clientName The client identifier used for the `c` parameter on every request.
 */
internal class SubsonicUrlBuilder(private val baseUrl: String, private val clientName: String) {

    /**
     * The current authenticator. Marked [Volatile] so a [setCredentials] call on one thread
     * is observable by [buildUrl] running on another (typically a coroutine on
     * [kotlinx.coroutines.Dispatchers.IO]).
     */
    @Volatile
    private var authenticator: SubsonicAuthenticator? = null

    /**
     * Replaces the stored credentials. All subsequent [buildUrl] calls use the new credentials.
     *
     * @param username The Subsonic username.
     * @param password The clear-text password.
     */
    fun setCredentials(username: String, password: String) {
        authenticator = SubsonicAuthenticator(
            username = username,
            password = password,
            clientName = clientName
        )
    }

    /**
     * Builds the full URL for an API endpoint, with credentials applied.
     *
     * The URL is composed of, in order: the base URL, the `rest/<endpoint>` path, the
     * mandatory `f=json` parameter, the caller-supplied [params] (one pair per entry),
     * the caller-supplied [multiValueParams] (one pair per value, so a key with three
     * values appears three times in the query string), and finally the authentication
     * parameters from the current [SubsonicAuthenticator].
     *
     * @param endpoint The API method name (e.g. `"ping"`).
     * @param params Single-value query parameters for the endpoint.
     * @param multiValueParams Multi-value query parameters where one key maps to many values.
     * @return The fully qualified, URL-encoded request URL.
     * @throws IllegalStateException If [setCredentials] has not been called.
     */
    fun buildUrl(
        endpoint: String,
        params: Map<String, String> = emptyMap(),
        multiValueParams: Map<String, List<String>> = emptyMap()
    ): String {
        val authParams = authenticator?.generateAuthParams()
            ?: throw IllegalStateException("Credentials not set. Call setCredentials() first.")

        val normalizedBaseUrl = if (baseUrl.endsWith("/")) baseUrl else "$baseUrl/"
        return buildString {
            append(normalizedBaseUrl).append("rest/").append(endpoint).append("?f=json")
            params.forEach { (key, value) -> appendParam(key, value) }
            multiValueParams.forEach { (key, values) ->
                values.forEach { value -> appendParam(key, value) }
            }
            authParams.forEach { (key, value) -> appendParam(key, value) }
        }
    }

    private fun StringBuilder.appendParam(key: String, value: String) {
        append("&").append(key).append("=").append(URLEncoder.encode(value, "UTF-8"))
    }
}
